apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-forgejo-migration-source
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-static
  volumeName: gitea-forgejo-migration-source
