apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo-runner
resources:
  - ./resources/namespace.yaml
  - ./resources/external-secret.yaml
  - ./resources/network-policy.yaml
  - ./resources/trigger-authentication.yaml
  - ./resources/scaled-job.yaml
