apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3
  namespace: loki
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: loki-s3
  data:
    - secretKey: endpoint
      remoteRef:
        key: loki
        property: s3_endpoint
    - secretKey: region
      remoteRef:
        key: loki
        property: s3_region
    - secretKey: access_key_id
      remoteRef:
        key: loki
        property: s3_access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: loki
        property: s3_secret_access_key
