apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - ./resources/namespace.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "67.3.2"
    releaseName: prometheus
    namespace: prometheus
    valuesInline:
      grafana:
        enabled: false

      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi

      alertmanager:
        alertmanagerSpec:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi

      nodeExporter:
        enabled: true

      kubeStateMetrics:
        enabled: true
