apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tempo
resources:
  - ./resources/namespace.yaml
helmCharts:
  - name: tempo
    repo: oci://ghcr.io/grafana-community/helm-charts
    version: "2.0.0"
    releaseName: tempo
    namespace: tempo
    valuesInline:
      tempo:
        storage:
          trace:
            backend: local
            local:
              path: /var/tempo/traces
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi

      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi
