apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
resources:
  - external-secret.yaml
helmCharts:
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: "10.4.3"
    releaseName: oauth2-proxy
    namespace: oauth2-proxy
    valuesInline:
      config:
        existingSecret: oauth2-proxy

      extraArgs:
        provider: oidc
        oidc-issuer-url: https://zitadel.poporon.org
        redirect-url: https://oauthproxy.poporon.org/oauth2/callback
        upstream: "static://202"
        email-domain: "*"
        skip-provider-button: "true"
        reverse-proxy: "true"
        cookie-secure: "true"
        cookie-domain: ".poporon.org"
        scope: "openid profile email"
        whitelist-domain: ".poporon.org"
        cookie-csrf-per-request: "true"
        cookie-csrf-expire: "5m"

      ingress:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - oauthproxy.poporon.org
        tls:
          - secretName: wildcard-poporon-org-tls
            hosts:
              - oauthproxy.poporon.org

      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi
