apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp
  namespace: headlamp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: headlamp
  data:
    - secretKey: oidc-client-id
      remoteRef:
        key: headlamp
        property: oidc_client_id
    - secretKey: oidc-client-secret
      remoteRef:
        key: headlamp
        property: oidc_client_secret
