apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-config
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: forgejo-config
    template:
      engineVersion: v2
      data:
        database-password: "{{ .database_password }}"
        secret-key: "{{ .secret_key }}"
        internal-token: "{{ .internal_token }}"
        oauth2-jwt-secret: "{{ .oauth2_jwt_secret }}"
        lfs-jwt-secret: "{{ .lfs_jwt_secret }}"
        valkey-queue-uri: "redis://default:{{ .valkey_password | urlquery }}@valkey.valkey.svc.cluster.local:6379/0"
        valkey-cache-uri: "redis://default:{{ .valkey_password | urlquery }}@valkey.valkey.svc.cluster.local:6379/1"
        valkey-session-uri: "redis://default:{{ .valkey_password | urlquery }}@valkey.valkey.svc.cluster.local:6379/2"
  data:
    - secretKey: database_password
      remoteRef:
        key: forgejo
        property: database_password
    - secretKey: secret_key
      remoteRef:
        key: forgejo
        property: secret_key
    - secretKey: internal_token
      remoteRef:
        key: forgejo
        property: internal_token
    - secretKey: oauth2_jwt_secret
      remoteRef:
        key: forgejo
        property: oauth2_jwt_secret
    - secretKey: lfs_jwt_secret
      remoteRef:
        key: forgejo
        property: lfs_jwt_secret
    - secretKey: valkey_password
      remoteRef:
        key: valkey
        property: password
