apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: grafana
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.poporon.org
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
