apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "http://10.33.2.20:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: vault-approle
            namespace: external-secrets
            key: roleId
          secretRef:
            name: vault-approle
            namespace: external-secrets
            key: secretId
