apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel
  namespace: zitadel
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: zitadel
    template:
      data:
        masterkey: "{{ .masterkey }}"
        config.yaml: |
          Database:
            Postgres:
              User:
                Password: {{ .db_user_password | quote }}
              Admin:
                Password: {{ .db_admin_password | quote }}
  data:
    - secretKey: masterkey
      remoteRef:
        key: zitadel
        property: masterkey
    - secretKey: db_user_password
      remoteRef:
        key: zitadel
        property: db_user_password
    - secretKey: db_admin_password
      remoteRef:
        key: zitadel
        property: db_admin_password
