apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: argocd-oidc
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: client_id
      remoteRef:
        key: argocd-oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: argocd-oidc
        property: client_secret
