apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valkey
  namespace: valkey
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: valkey
  data:
    - secretKey: default
      remoteRef:
        key: valkey
        property: password
