apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:aQUi1vh6bW2880nhW1gwKnitIiqlnAfdTypIiEEFtybvhy2vQeuUNA==,iv:Fpr4+j9F1RLiYHkIzSAcoZ/twxb0/SCM7c9qgBvkbS0=,tag:A2ODH5Tk9TYciDR0wEwcmA==,type:str]
sops:
    age:
        - recipient: age1y5ats7ej350qeylfcw49wjtwkdz9ll3gqgeeyx7emgyp9f3uyuwq5jl4jh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RGdjd0hiQk15QzNTb3l0
            OE5Jck9Hcm5hMVc0VUFtT0ZTcnRTUTIxU2lBCm9CYXd1aWhsU2ZyMC96VmQ4b1FR
            TWRqeGFmYlJkVWZVQXVzNXNCT0swZmsKLS0tIFBvanIwalR6VDhWTkQra0pvY2cr
            dEk1NEduY0NHV2xJaERSdlBhMDd1OFEKDAcT6NVMkeIaUJVbAob7cr9WYVXU7Ci1
            GZHOxbq3rdVkK3SvuPSGGfsApedf/EHL27apsIYqpJpe2EwfFBdM2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T17:13:16Z"
    mac: ENC[AES256_GCM,data:ka4eA8vHQA8w9pcUEt4CVhMaRFBIn25IxoTFGd4hmIQk4utEqIHIycEz7SZRMhGik4td3knBJGfPf3VFjwAc12ntXDtCOZjW4vYp5jXant8fTm7HY8bUzSnR9ytKY/bsypw7gyIeKHK9wStLG1P4ZncPiz185VKdDnM28yMrHqw=,iv:2SaRXYo3R/80IQtZqtX3Au+h9vFjWntLozTOvkm6dhk=,tag:7hF5bOQZ9ddT6DfdxkB5hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
