apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudflare-api-token
    template:
      type: Opaque
      data:
        api-token: "{{ .token }}"
  dataFrom:
    - extract:
        key: traefik
