apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: forgejo-runner
    template:
      engineVersion: v2
      data:
        keda-api-token: "{{ .api_token }}"
        runner-config.yaml: |
          log:
            level: info
            job_level: info

          runner:
            capacity: 1
            envs:
              DOCKER_HOST: tcp://localhost:2376
              DOCKER_TLS_CERTDIR: /certs
              DOCKER_CERT_PATH: /certs/client
              DOCKER_TLS_VERIFY: "1"
            timeout: 3h
            shutdown_timeout: 5m
            labels:
              - ubuntu-latest:docker://git.poporon.org/poporonnet/runner-image:latest

          cache:
            enabled: false

          container:
            network: host
            privileged: false
            options: -v /certs/client:/certs/client:ro
            valid_volumes:
              - /certs/client
            docker_host: tcp://localhost:2376
            force_pull: true

          server:
            connections:
              forgejo:
                url: https://git.poporon.org/
                uuid: "{{ .runner_uuid }}"
                token: "{{ .runner_token }}"
  data:
    - secretKey: api_token
      remoteRef:
        key: forgejo-runner
        property: api_token
    - secretKey: runner_uuid
      remoteRef:
        key: forgejo-runner
        property: runner_uuid
    - secretKey: runner_token
      remoteRef:
        key: forgejo-runner
        property: runner_token
