apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
spec:
  secretTargetRef:
    - parameter: token
      name: forgejo-runner
      key: keda-api-token
