apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oOVBDrktwmGXAia301WOf3DWN58ksyC/5KucXEVAYX+rQI+FV5CGKQ==,iv:2GYnGA6nyxp85WZ9sN6HDK1YGVQsyKwcJPrWzY47b3Q=,tag:rtnZWeU7p+GfChNyZciNag==,type:str]
sops:
    age:
        - recipient: age1gpcnrw2vat84f560gv2xjajlugn88qjsd420wtdarn4alylm89gq08jwgf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdmdHUlp3NzRWUG9CUnhJ
            YWJJaU5mODRPU1RDVEJLSmdFNEpocWFyOUZVClhJSk5FNnRodXVvc0h2ZTVRdmRo
            LzJNd1pWRlFmMVNYWHdmdk4rOU5JL0kKLS0tIDdSNEhsWGxSSEU3b3FzSzEwM2x4
            V3J6d0F2RytjSXZGR1J4c0dsQmhxTzgKI8+cPxxYVX092tRCAnfb9ixIH1cV8ZxQ
            7c2BD+cXcUWPnzr/O13iHdjWQR1MlPd1NcdfpYjp3RYZmyQgfW2UpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T17:08:02Z"
    mac: ENC[AES256_GCM,data:Pn7tvtBtW3GPzE5VQB0DnYF9+ALlKkrPJn3hpyO9wgfZrERl/6bmdCJSeCJfIA3z04TutIZs5rQ1NzSd786D5I4doYO0amqHrLRh+yOgQqmqJHRHYL46Yf8b8VrNeLQHiQDE7D9umffOti8sRPd1l7QCka2OKWEX8Gf87GV8TDE=,iv:Vof8R0Bp/1pUZFG+SV9EwLOTGNsrhLCPk1tVBQtkWJM=,tag:AUtI0JAZCyL05wbi/X3M7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
