apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:IMivSxRHqViynJnA8EHleQ5rp5BonBsV84FHbT3vONWvs4K014g91w==,iv:2taK2UOs0gSfJwKO92ZrrFFdp2MbrltnFlWaLzIgKq8=,tag:4au27Y69NqZxEisU2bygdg==,type:str]
sops:
    age:
        - recipient: age1y5ats7ej350qeylfcw49wjtwkdz9ll3gqgeeyx7emgyp9f3uyuwq5jl4jh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTEQxV09IOVBIN0N0YW5u
            Y2xqZWdwdXJWbUo2ZVBQYWxoRXFRMEFkanlzCkZYcE1VUHlvSTV6NXoydk95a09x
            bi8ySm9DYVUxZDRkaExQN0c0Qkh6dEkKLS0tIFgrWGtiUk4rTzJPemZ0dElqdzNa
            ZFRVTGJzaTJOdUV3VzNjY1BmWmpkZHMK0sKo7LJ+Qqmck6eIs+qna5X53/WRmZhs
            Ew7wMtV7BsTLhhFVmkjOwusP/jRjCZHHAOUBfjK474uEL2vFOu6HEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T16:34:02Z"
    mac: ENC[AES256_GCM,data:qbr6PXfcjhfCxmF87V1pDBYK7KCJWxnA9ffR/0mpIQLLT+YTnb6ufhXejBTWVnZZX2ugN4uNQuomtVnZFjmRHikWbQGCDLR/92F24Nrohgy168m6Vr2cAesXuPp21+CX6q0s8R3RGMuYAIpMwwXNcjeGF4oKwR9gQZmBi/AjHAc=,iv:tbSj1c6Osd/8NPefjSu2w/2tNjHM84fUKXpvy4jlop8=,tag:JNTCVSkYmFRE+8UW3e5pvA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
