apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - ./resources/namespace.yaml
  - ./resources/external-secret.yaml
  - ./resources/ingress.yaml
  - ./resources/pv.yaml
helmCharts:
  - name: grafana
    repo: oci://ghcr.io/grafana-community/helm-charts
    version: "11.6.1"
    releaseName: grafana
    namespace: grafana
    valuesInline:
      admin:
        existingSecret: grafana
        userKey: admin-user
        passwordKey: admin-password

      initChownData:
        enabled: false

      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi

      grafana.ini:
        log:
          level: debug
        server:
          domain: grafana.poporon.org
          root_url: https://grafana.poporon.org
        auth:
          disable_login_form: false
        auth.generic_oauth:
          enabled: true
          name: Zitadel
          allow_sign_up: true
          scopes: openid profile email roles
          auth_url: https://zitadel.poporon.org/oauth/v2/authorize
          token_url: https://zitadel.poporon.org/oauth/v2/token
          api_url: https://zitadel.poporon.org/oidc/v1/userinfo
          client_id: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
          use_pkce: true
          role_attribute_path: '"urn:zitadel:iam:org:project:roles".admin && ''Admin'' || ''Viewer'''
          use_id_token: true

      envFromSecret: grafana

      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - grafana.poporon.org
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.poporon.org

      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 256Mi
